/*
 * Aston API
 * API principale de la communauté d'Aston
 *
 * OpenAPI spec version: 1.0.11
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The User model module.
 * @module model/User
 * @version 1.0.11
 */
export class User {
  /**
   * Constructs a new <code>User</code>.
   * @alias module:model/User
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/User} obj Optional instance to populate.
   * @return {module:model/User} The populated <code>User</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new User();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('rpname'))
        obj.rpname = ApiClient.convertToType(data['rpname'], 'String');
      if (data.hasOwnProperty('money'))
        obj.money = ApiClient.convertToType(data['money'], 'Number');
      if (data.hasOwnProperty('bank'))
        obj.bank = ApiClient.convertToType(data['bank'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
User.prototype.id = undefined;

/**
 * @member {String} rpname
 */
User.prototype.rpname = undefined;

/**
 * @member {Number} money
 */
User.prototype.money = undefined;

/**
 * @member {Number} bank
 */
User.prototype.bank = undefined;

