/*
 * Aston API
 * API principale de la communauté d'Aston
 *
 * OpenAPI spec version: 1.0.11
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AstonApi);
  }
}(this, function(expect, AstonApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('User', function() {
      beforeEach(function() {
        instance = new AstonApi.User();
      });

      it('should create an instance of User', function() {
        // TODO: update the code to test User
        expect(instance).to.be.a(AstonApi.User);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property rpname (base name: "rpname")', function() {
        // TODO: update the code to test the property rpname
        expect(instance).to.have.property('rpname');
        // expect(instance.rpname).to.be(expectedValueLiteral);
      });

      it('should have the property money (base name: "money")', function() {
        // TODO: update the code to test the property money
        expect(instance).to.have.property('money');
        // expect(instance.money).to.be(expectedValueLiteral);
      });

      it('should have the property bank (base name: "bank")', function() {
        // TODO: update the code to test the property bank
        expect(instance).to.have.property('bank');
        // expect(instance.bank).to.be(expectedValueLiteral);
      });

    });
  });

}));
